#Default values for go-web-app-chart
#This is a YAML-formatted file.
#Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: suryapradeepthi9846/go-web-app
  pullpolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion
  tag: "10606136416"
ingress:
  enabled: false
  className: ""
  annotations: {}
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  hosts:
    - hosts: chart-example.local
      paths:
       - path: /
         pathType: ImplementationSpecific

